from typing import Any

DECODE_AND_MERGE: Any

class RenderSetup:
    def importAllFromFile(self, *args: Any) -> None: ...
    def getRenderLayer(self, *args: Any) -> Any: ...
    def switchToLayer(self, *args: Any) -> None: ...

def instance() -> RenderSetup: ...
