#!/usr/bin/env python3
"""Move logs of successful scripts into the 'success/' directory"""

from argparse import ArgumentParser
from pathlib import Path


def _has_traceback(file: Path) -> bool:
    with file.open("r", encoding="utf-8") as f:
        for line in f:
            if "Traceback" in line:
                return True
    return False


def main(dir: Path) -> None:
    log_files = (f for f in dir.iterdir() if f.suffix == ".log")
    for log in log_files:
        if not _has_traceback(log):
            log.rename(f"{dir}/success/{log.name}")


if __name__ == "__main__":
    parser = ArgumentParser(
        prog="Successful Logs Archiver", description=__doc__
    )
    parser.add_argument("dir", type=Path, help="Directory containing log files")
    args = parser.parse_args()
    main(args.dir)
