#!/bin/zsh
# Send a Python script to Maya via a socket opened by `commandPort`
# The script must be under src/rec/, and the socket must be /tmp/vscodeToMaya

source "${0:h}/errorMessage.zsh"

readonly SOCKET=/tmp/vscodeToMaya

if [[ ! -S "${SOCKET}" ]]; then
  err "${0:t}: ${SOCKET}: Not a socket"
elif [[ ! -f "$1" ]]; then
  err "${0:t}: ${1:P}: Not a file"
elif [[ "${1:e}" != 'py' ]]; then
  err "${0:t}: ${1:P}: Not a Python file"
fi;

readonly parentDir="${1:h:t}"
if [[ "${parentDir}" != 'rec' ]]; then
  err "${0:t}: Script must be from src/rec/"
fi;

cat << END | nc -U "${SOCKET}"
from ${parentDir}.${1:t:r} import main

main()
END