#!/bin/zsh

################################################################################
# Delete local and Google Drive log files older than two weeks
################################################################################

source "${0:h}/directories.zsh"

deleteOldLogs() {
  find "$1" -type f -name '*.log' -Btime +2w -delete
}

deleteOldLogs "${localScriptsDir}"
deleteOldLogs "${gDriveScriptsDir}"