#!/bin/zsh

################################################################################
# Delete logs older than two weeks
################################################################################

source "${0:h}/errorMessage.zsh"

if (( "$#" < 1 )); then
  errorMessage "${0:t}: No directories given"
fi

for dir in "$@"; do
  if [[ ! -d "$d" ]]; then
    continue
  fi
  find "$dir" -type f -name '*.log' -Btime +2w -delete
done