#!/bin/zsh

################################################################################
# Sync the scripts to the Google shared drive
################################################################################

source "${0:h}/directories.zsh"

declare -a NAMES_TO_EXCLUDE args
readonly NAMES_TO_EXCLUDE=('.DS_Store' '__pycache__' 'logs/')

args=(--archive)
if [[ "$1" == '-n' || "$1" == '--dry-run' ]]; then
  args+=(--dry-run --verbose)
elif [[ -n "$1" ]]; then
  echo "${0:t}: Only valid flag is '-n' or '--dry-run'" >&2
  exit 1
fi

for name in "${NAMES_TO_EXCLUDE[@]}"; do
  args+=(--exclude="${name}")
done

rsync "${args[@]}" "${localScriptsDir}/" "${gDriveScriptsDir}"