#!/bin/zsh

################################################################################
# Sync the scripts to the specified directory
################################################################################

source "${0:h}/errorMessage.zsh"

declare -a NAMES_TO_EXCLUDE args
readonly NAMES_TO_EXCLUDE=('.DS_Store' '__pycache__' 'logs/')

args=(--archive)
if (( "$#" > 1 )) && ! [[ "$1" == '-n' || "$1" == '--dry-run' ]]; then
  errorMessage "${0:t}: Only valid optional flag is '-n' or '--dry-run'"
else
  args+=(--dry-run --verbose)
elif [[ -n "$1" ]]; then
  echo "${0:t}: Only valid flag is '-n' or '--dry-run'" >&2
  exit 1
fi

for name in "${NAMES_TO_EXCLUDE[@]}"; do
  args+=(--exclude="${name}")
done

rsync "${args[@]}" "${0:h:h}/src/" "$1"