#!/usr/bin/env zsh
# Batch render Maya scenes from the queue

readonly SCRIPT="${0:A:h}/rec/render.py"

while (true); do
  renderArgs="$(${SCRIPT})"

  if [[ -z "${renderArgs}" ]]; then
    break
  fi

  "${(s/,/)renderArgs}"
done
