#!/usr/bin/env zsh
# Batch render Maya scenes from the queue

readonly SCRIPT_DIR="${0:A:h}"
readonly SCRIPT="${SCRIPT_DIR}/rec/construct_renderArgs.py"
readonly CMD="${SCRIPT_DIR}/__render.zsh"

while true; do
  "${SCRIPT}" "${CMD}" || break
  zsh "${CMD}"
done
